// Digital Logic Design Problems - LeetCode style

const problemsData = [
  {
    id: 1,
    title: "Half Adder",
    difficulty: "Easy",
    tags: ["Combinational", "Arithmetic"],
    description:
      "Design a Half Adder circuit that takes two 1-bit inputs A and B, and produces a Sum (S) and Carry (C) output.",
    truthTable: [
      { A: 0, B: 0, S: 0, C: 0 },
      { A: 0, B: 1, S: 1, C: 0 },
      { A: 1, B: 0, S: 1, C: 0 },
      { A: 1, B: 1, S: 0, C: 1 },
    ],
    equations: ["S = A ⊕ B", "C = A · B"],
    hint: "Sum uses XOR, Carry uses AND.",
    inputs: ["A", "B"],
    outputs: ["S", "C"],
  },
  {
    id: 2,
    title: "Full Adder",
    difficulty: "Easy",
    tags: ["Combinational", "Arithmetic"],
    description:
      "Design a Full Adder with inputs A, B, and Carry-In (Cin), producing Sum (S) and Carry-Out (Cout).",
    truthTable: [
      { A: 0, B: 0, Cin: 0, S: 0, Cout: 0 },
      { A: 0, B: 0, Cin: 1, S: 1, Cout: 0 },
      { A: 0, B: 1, Cin: 0, S: 1, Cout: 0 },
      { A: 0, B: 1, Cin: 1, S: 0, Cout: 1 },
      { A: 1, B: 0, Cin: 0, S: 1, Cout: 0 },
      { A: 1, B: 0, Cin: 1, S: 0, Cout: 1 },
      { A: 1, B: 1, Cin: 0, S: 0, Cout: 1 },
      { A: 1, B: 1, Cin: 1, S: 1, Cout: 1 },
    ],
    equations: ["S = A ⊕ B ⊕ Cin", "Cout = AB + BCin + ACin"],
    hint: "Combine two Half Adders with an OR gate for Carry-Out.",
    inputs: ["A", "B", "Cin"],
    outputs: ["S", "Cout"],
  },
  {
    id: 3,
    title: "2-to-1 Multiplexer",
    difficulty: "Easy",
    tags: ["Combinational", "MUX"],
    description:
      "Build a 2-to-1 MUX with inputs I0, I1 and select line S. Output Y = I0 when S=0, Y = I1 when S=1.",
    truthTable: [
      { S: 0, I0: 0, I1: 0, Y: 0 },
      { S: 0, I0: 1, I1: 0, Y: 1 },
      { S: 1, I0: 0, I1: 0, Y: 0 },
      { S: 1, I0: 0, I1: 1, Y: 1 },
    ],
    equations: ["Y = S'·I0 + S·I1"],
    hint: "Use two AND gates, one NOT gate, and one OR gate.",
    inputs: ["S", "I0", "I1"],
    outputs: ["Y"],
  },
  {
    id: 4,
    title: "4-to-1 Multiplexer",
    difficulty: "Medium",
    tags: ["Combinational", "MUX"],
    description:
      "Design a 4-to-1 MUX with 4 data inputs (I0–I3), 2 select lines (S1, S0), and one output Y.",
    truthTable: [
      { S1: 0, S0: 0, Y: "I0" },
      { S1: 0, S0: 1, Y: "I1" },
      { S1: 1, S0: 0, Y: "I2" },
      { S1: 1, S0: 1, Y: "I3" },
    ],
    equations: ["Y = S1'S0'·I0 + S1'S0·I1 + S1S0'·I2 + S1S0·I3"],
    hint: "Use four AND gates (3-input each), one OR gate (4-input), and NOT gates for S1 and S0.",
    inputs: ["S1", "S0", "I0", "I1", "I2", "I3"],
    outputs: ["Y"],
  },
  {
    id: 5,
    title: "1-to-2 Demultiplexer",
    difficulty: "Easy",
    tags: ["Combinational", "DEMUX"],
    description:
      "Build a 1-to-2 DEMUX. Route a single input D to one of two outputs (Y0, Y1) based on select S.",
    truthTable: [
      { S: 0, D: 0, Y0: 0, Y1: 0 },
      { S: 0, D: 1, Y0: 1, Y1: 0 },
      { S: 1, D: 0, Y0: 0, Y1: 0 },
      { S: 1, D: 1, Y0: 0, Y1: 1 },
    ],
    equations: ["Y0 = D·S'", "Y1 = D·S"],
    hint: "Two AND gates with NOT gate on S for Y0.",
    inputs: ["D", "S"],
    outputs: ["Y0", "Y1"],
  },
  {
    id: 6,
    title: "2-to-4 Decoder",
    difficulty: "Medium",
    tags: ["Combinational", "Decoder"],
    description:
      "Design a 2-to-4 decoder with inputs A1, A0 and an active-high enable E. Outputs D0–D3.",
    truthTable: [
      { E: 0, A1: "X", A0: "X", D0: 0, D1: 0, D2: 0, D3: 0 },
      { E: 1, A1: 0, A0: 0, D0: 1, D1: 0, D2: 0, D3: 0 },
      { E: 1, A1: 0, A0: 1, D0: 0, D1: 1, D2: 0, D3: 0 },
      { E: 1, A1: 1, A0: 0, D0: 0, D1: 0, D2: 1, D3: 0 },
      { E: 1, A1: 1, A0: 1, D0: 0, D1: 0, D2: 1, D3: 1 },
    ],
    equations: [
      "D0 = E·A1'·A0'",
      "D1 = E·A1'·A0",
      "D2 = E·A1·A0'",
      "D3 = E·A1·A0",
    ],
    hint: "Each output is a minterm AND-ed with the enable signal.",
    inputs: ["E", "A1", "A0"],
    outputs: ["D0", "D1", "D2", "D3"],
  },
  {
    id: 7,
    title: "SR Latch (NOR-based)",
    difficulty: "Medium",
    tags: ["Sequential", "Latch"],
    description:
      "Build a basic SR Latch using two cross-coupled NOR gates. S=Set, R=Reset, Q and Q' are outputs.",
    truthTable: [
      { S: 0, R: 0, Q: "Q_prev", "Q'": "Q'_prev" },
      { S: 0, R: 1, Q: 0, "Q'": 1 },
      { S: 1, R: 0, Q: 1, "Q'": 0 },
      { S: 1, R: 1, Q: "?", "Q'": "?" },
    ],
    equations: ["Q = (R + Q')'", "Q' = (S + Q)'"],
    hint: "Two NOR gates cross-coupled: output of each feeds back into the other's input.",
    inputs: ["S", "R"],
    outputs: ["Q", "Q'"],
  },
  {
    id: 8,
    title: "Odd Parity Generator (3-bit)",
    difficulty: "Medium",
    tags: ["Combinational", "Parity"],
    description:
      "Design a 3-bit odd parity generator. Given inputs A, B, C — output P such that the total number of 1s (A, B, C, P) is always odd.",
    truthTable: [
      { A: 0, B: 0, C: 0, P: 1 },
      { A: 0, B: 0, C: 1, P: 0 },
      { A: 0, B: 1, C: 0, P: 0 },
      { A: 0, B: 1, C: 1, P: 1 },
      { A: 1, B: 0, C: 0, P: 0 },
      { A: 1, B: 0, C: 1, P: 1 },
      { A: 1, B: 1, C: 0, P: 1 },
      { A: 1, B: 1, C: 1, P: 0 },
    ],
    equations: ["P = A ⊕ B ⊕ C ⊕ 1", "P = (A ⊕ B ⊕ C)'"],
    hint: "XOR all inputs together, then invert the result for odd parity.",
    inputs: ["A", "B", "C"],
    outputs: ["P"],
  },
];

export default problemsData;
